apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-rubyapp
  namespace: demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-rubyapp
    spec:
      containers:
      - name: rubyapp
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cloud-platform/reference-app:demo-sinatra
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
