apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rubyapp-ingress
  namespace: demo-app
spec:
  tls:
  - hosts:
    - demo-sinatra.apps.test-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: demo-sinatra.apps.test-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
